# Generated by Django 6.0.5 on 2026-05-13 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('safra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('termo', 'Contrato a Termo'), ('cpr', 'CPR (Cédula de Produto Rural)'), ('balcao', 'Venda Balcão'), ('futuro_b3', 'Futuro B3'), ('opcao_b3', 'Opção B3')], max_length=20)),
                ('contraparte', models.CharField(help_text='Cargill, Coopercitrus, BB, etc.', max_length=120)),
                ('sacas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preco_por_saca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_negociacao', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='safra.safra')),
            ],
            options={
                'ordering': ['-data_negociacao'],
            },
        ),
    ]
