# Generated by Django 6.0.5 on 2026-05-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtor',
            options={'verbose_name': 'Produtor', 'verbose_name_plural': 'Produtores'},
        ),
        migrations.AddField(
            model_name='produtor',
            name='aceitou_termos_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produtor',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='produtor',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='produtor',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
