# Generated by Django 6.0.5 on 2026-05-13 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Safra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(choices=[('soja', 'Soja'), ('milho', 'Milho'), ('cafe', 'Café'), ('cana', 'Cana-de-açúcar'), ('trigo', 'Trigo')], max_length=20)),
                ('ano_safra', models.CharField(help_text='Ex: 2025/26', max_length=10)),
                ('producao_estimada_sacas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('custo_por_saca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criada_em'],
                'unique_together': {('produtor', 'cultura', 'ano_safra')},
            },
        ),
    ]
