# Generated by Django 6.0.5 on 2026-05-17 21:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safra',
            name='pct_insumos_dolar',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='% do custo de insumos atrelado ao dólar (0–100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='safra',
            name='preco_referencia_local',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço local informado pelo produtor (cooperativa/trader), R$/sc', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='safra',
            name='total_insumos_brl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo total de insumos da safra (R$)', max_digits=14, null=True),
        ),
    ]
